version: '3.8'

services:
  kuard-blue:
    image: ongoonku/kuard-amd64:blue
    container_name: kuard-blue
    ports:
      - "8888:8080"
    restart: unless-stopped

  kuard-green:
    image: ongoonku/kuard-amd64:green
    container_name: kuard-green
    ports:
      - "8889:8080"
    restart: unless-stopped

  kuard-purple:
    image: ongoonku/kuard-amd64:purple
    container_name: kuard-purple
    ports:
      - "8890:8080"
    restart: unless-stopped
